apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: standalone
  name: standalone
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: standalone
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/rubra: "true"
        io.kompose.service: standalone
    spec:
      containers:
        - args:
            - milvus
            - run
            - standalone
          env:
            - name: COMMON_STORAGETYPE
              value: local
            - name: ETCD_CONFIG_PATH
              value: /milvus/configs/embedEtcd.yaml
            - name: ETCD_DATA_DIR
              value: /etcd
            - name: ETCD_USE_EMBED
              value: "true"
          image: milvusdb/milvus:v2.3.3
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:9091/healthz
            failureThreshold: 3
            initialDelaySeconds: 90
            periodSeconds: 30
            timeoutSeconds: 20
          name: milvus
          ports:
            - containerPort: 19530
              hostPort: 19530
              protocol: TCP
            - containerPort: 9091
              hostPort: 9091
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/milvus
              name: milvus
            - mountPath: /milvus/configs/milvus.yaml
              name: standalone-claim1
            - mountPath: /etcd
              name: etcd
            - mountPath: /milvus/configs/embedEtcd.yaml
              name: standalone-claim3
      restartPolicy: Always
      volumes:
        - name: milvus
          persistentVolumeClaim:
            claimName: milvus
        - name: standalone-claim1
          persistentVolumeClaim:
            claimName: standalone-claim1
        - name: etcd
          persistentVolumeClaim:
            claimName: etcd
        - name: standalone-claim3
          persistentVolumeClaim:
            claimName: standalone-claim3
