apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: ui
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ui
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/rubra: "true"
        io.kompose.service: ui
    spec:
      containers:
        - env:
            - name: RUBRA_BACKEND_HOST
              value: api-server
          image: ghcr.io/rubra-ai/rubra/ui:main
          name: ui
          ports:
            - containerPort: 8501
              hostPort: 8501
              protocol: TCP
      restartPolicy: Always
