apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: vector-db-api
  name: vector-db-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vector-db-api
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/rubra: "true"
        io.kompose.service: vector-db-api
    spec:
      containers:
        - env:
            - name: EMBEDDING_HOST
              value: text-embedding-api
            - name: MILVUS_HOST
              value: milvus
          image: ghcr.io/rubra-ai/rubra/vector_db_api:main
          name: vector-db-api
          ports:
            - containerPort: 8010
              hostPort: 8010
              protocol: TCP
      restartPolicy: Always
