model_list:
  # Local Model
  - model_name: custom
    litellm_params:
      model: openai/custom
      api_base: "http://host.docker.internal:1234/v1"
      api_key: "None"
      custom_llm_provider: "openai"

  # OpenAI GPT-4
  # - model_name: gpt-4-1106-preview
  #   litellm_params:
  #     model: gpt-4-1106-preview
  #     api_key: "OPENAI_API_KEY"
  #     custom_llm_provider: "openai"

  # Anthropic Claude
  # - model_name: claude-2.1
  #   litellm_params:
  #     model: claude-2.1
  #     api_key: "ANTHROPIC_API_KEY"

litellm_settings:
  drop_params: True
  set_verbose: True
  cache: True

environment_variables:
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: ""
